// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wngkhgokjcharefxglzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZ2toZ29ramNoYXJlZnhnbHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDcwNTQsImV4cCI6MjA2MDU4MzA1NH0.UxOQ7f5RFNgqADUm9wYvj2nSE5R5coQ9fnV_ou1fvZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);